version: '3.8'

services:
  db-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_hotel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"

  web-test:
    build: .
    environment:
      - DEBUG=True
      - SECRET_KEY=test-key
      - DJANGO_ALLOWED_HOSTS=localhost
      - DB_NAME=test_hotel_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_HOST=db-test
      - DB_PORT=5432
    depends_on:
      - db-test
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             pytest"